/* empty css                      */import{a as g,S as L,i as s}from"./assets/vendor-73qhTu8_.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function i(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(o){if(o.ep)return;o.ep=!0;const r=i(o);fetch(o.href,r)}})();const b="55667978-30b86439af915a57195a8c60a",S="https://pixabay.com/api/";async function u(e,t){return(await g.get(S,{params:{key:b,q:e,page:t,image_type:"photo",orientation:"horizontal",per_page:15}})).data}const w=new L(".gallery a",{captionsData:"alt",captionDelay:250});function f(e){const t=document.querySelector(".gallery"),i=e.map(n=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${n.largeImageURL}">
          <img class="gallery-image" src="${n.webformatURL}" alt="${n.tags}" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b>${n.likes}</p>
          <p class="info-item"><b>Views</b>${n.views}</p>
          <p class="info-item"><b>Comments</b>${n.comments}</p>
          <p class="info-item"><b>Downloads</b>${n.downloads}</p>
        </div>
      </li>`).join("");t.insertAdjacentHTML("beforeend",i),w.refresh()}function q(){const e=document.querySelector(".gallery");e&&(e.innerHTML="")}function m(){const e=document.querySelector(".loader");e&&e.classList.remove("is-hidden")}function y(){const e=document.querySelector(".loader");e&&e.classList.add("is-hidden")}function v(){const e=document.querySelector(".load-more");e&&e.classList.remove("is-hidden")}function d(){const e=document.querySelector(".load-more");e&&e.classList.add("is-hidden")}const h=document.querySelector(".form"),M=document.querySelector(".load-more"),P=document.querySelector(".search-text");let c="",a=1;const B=15;h.addEventListener("submit",E);M.addEventListener("click",$);async function E(e){if(e.preventDefault(),c=P.value.trim(),c===""){s.warning({title:"Caution",message:"Please enter a search query!"});return}a=1,q(),d(),m();try{const t=await u(c,a);if(t.hits.length===0){s.error({message:"Sorry, there are no images matching your search query. Please, try again.",position:"topRight"});return}f(t.hits),p(t.totalHits)}catch{s.error({title:"Error",message:"Something went wrong!"})}finally{y(),h.reset()}}async function $(){a+=1,d(),m();try{const e=await u(c,a);f(e.hits),O(),p(e.totalHits)}catch{s.error({message:"Error loading more images!"})}finally{y()}}function p(e){const t=Math.ceil(e/B);a>=t?(d(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v()}function O(){const e=document.querySelector(".gallery-item");if(e){const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
